### ISSUE TITLE
Migrations not working with py3.4 django1.7 

### ISSUE THREAD

**Issue by rimek** [jdriscoll/django-photologue#114]
On version 3.1.dev0 migrations fails when using py3.4 django1.7 and mysql-connector-python==2.0.1
with:
```
  File "/home/users/rimek/.virtualenvs/dzwon-py3/lib/python3.4/site-packages/django_photologue-3.1.dev0-py3.4.egg/photologue/migrations/0005_auto_20141027_1552.py", line 18, in Migration
    preserve_default=True,
TypeError: __init__() got an unexpected keyword argument 'preserve_default'
```

Removing preserve_default option makes it work again

**Comment by richardbarran** [comment]
Closing this ticket now as I don't think anyone will be using Django 1.7.0 anymore.
